server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    discovery:
      enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: deposit-service
          uri: lb://deposit-service
          predicates:
            - Path=/auth/cards-products/**, /auth/deposit-cards/**, /auth/deposits/**, /auth/deposit-products/**, /auth/accounts/**
        - id: credit-service
          uri: lb://credit-service
          predicates:
            - Path=/credit-cards/**, /credits/**, /credit-orders/**, /credit-products/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/auth/**, /user-service/**, /security/session/**, /register/**, /user/settings/**
        - id: info-service
          uri: lb://info-service
          predicates:
            - Path=/bank-branch/**, /currency/**, /exchange-rates/**

eureka:
  instance:
    instance-id: ${spring.application.name}
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://10.10.14.11:9004/eureka

springdoc:
  api-docs:
    path: '/api-docs'
  swagger-ui:
    path: '/swagger-ui'
    operationsSorter: method
    urls:
      - name: deposit-service
        url: /deposit-service/api-docs
      - name: credit-service
        url: /credit-service/api-docs
      - name: user-service
        url: /user-service/api-docs
      - name: info-service
        url: /info-service/api-docs
  webjars:
    prefix: rmt-bank
