server:
  port: 8081

spring:
  main:
    web-application-type: reactive
    banner-mode: console
  application:
    name: api-gateway
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    discovery:
      enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: deposit
          uri: lb://deposit
          predicates:
            - Path=/auth/cards-products/**, /auth/deposit-cards/**, /auth/deposits/**, /auth/deposit-products/**, /auth/accounts/**
        - id: credit
          uri: lb://credit
          predicates:
            - Path=/credit-cards/**, /credits/**, /credit-orders/**, /credit-products/**
        - id: user
          uri: lb://user
          predicates:
            - Path=/auth/**, /user-service/**, /security/session/**, /register/**, /settings/**
        - id: info
          uri: lb://info
          predicates:
            - Path=/bank-branch/**, /currency/**, /exchange-rates/**

eureka:
  instance:
    instance-id: ${spring.application.name}
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8080/eureka

springdoc:
  api-docs:
    path: '/api-docs'
  swagger-ui:
    path: '/swagger-ui'
    operationsSorter: method
    urls:
      - name: deposit
        url: /deposit/api-docs
      - name: credit
        url: /credit/api-docs
      - name: user
        url: /user/api-docs
      - name: info
        url: /info/api-docs
  webjars:
    prefix: rmt-bank
