server:
  port: 8080

spring:
  main:
    web-application-type: reactive
    banner-mode: console
  application:
    name: api-gateway
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    discovery:
      enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: deposit
          uri: lb://deposit
          predicates:
            - Path=/api/v1/cards-products/**, /api/v1/deposit-cards/**, /api/v1/deposits/**, /api/v1/deposit-products/**, /api/v1/accounts/**
        - id: credit
          uri: lb://credit
          predicates:
            - Path=/api/v1/credit-cards/**, /api/v1/credits/**, /api/v1/credit-orders/**, /api/v1/credit-products/**
        - id: user
          uri: lb://user
          predicates:
            - Path=/api/v1//auth/**, /api/v1/user-service/**, /api/v1/security/session/**, /api/v1/register/**, /api/v1/user/settings/**
        - id: info
          uri: lb://info
          predicates:
            - Path=/api/v1/bank-branch/**, /api/v1/currency/**, /api/v1/exchange-rates/**

eureka:
  instance:
    instance-id: ${spring.application.name}
    preferIpAddress: true
    ip-address: ${server.address:10.10.14.53}
    non-secure-port: 9005
  client:
    serviceUrl:
      defaultZone: http://10.10.14.11:9004/eureka

springdoc:
  show-actuator: false
  use-management-port: false
  api-docs:
    path: '/api-docs'
  swagger-ui:
    path: '/swagger-ui'
    operationsSorter: method
    urls:
      - name: deposit
        url: /deposit/api-docs
      - name: credit
        url: /credit/api-docs
      - name: user
        url: /user/api-docs
      - name: info
        url: /info/api-docs
  webjars:
    prefix: rmt-bank
